const PHOTO_SETS = {
  "main-residence": [
    "assets/main-residence/main-exterior-hero.jpg",
    "assets/main-residence/main-living-hero.jpg",
    "assets/main-residence/main-kitchen-hero.jpg",
    "assets/main-residence/main-primary-bedroom-hero.jpg",
    "assets/main-residence/main-exterior-front-wide.jpg",
    "assets/main-residence/main-butler-kitchen.jpg",
    "assets/main-residence/main-downstairs-bathroom.jpg",
    "assets/main-residence/main-exterior-angle-01.jpg",
    "assets/main-residence/main-exterior-driveway.jpg",
    "assets/main-residence/main-guest-bathroom.jpg",
    "assets/main-residence/main-guest-bedroom-01.jpg",
    "assets/main-residence/main-guest-bedroom-02.jpg",
    "assets/main-residence/main-guest-bedroom-03.jpg",
    "assets/main-residence/main-guest-bedroom-04.jpg",
    "assets/main-residence/main-guest-bedroom-05.jpg",
    "assets/main-residence/main-hall-storage.jpg",
    "assets/main-residence/main-kitchen-counter.jpg",
    "assets/main-residence/main-kitchen-dining.jpg",
    "assets/main-residence/main-kitchen-range.jpg",
    "assets/main-residence/main-kitchen-wide-02.jpg",
    "assets/main-residence/main-kitchen-wide-03.jpg",
    "assets/main-residence/main-laundry.jpg",
    "assets/main-residence/main-living-01.jpg",
    "assets/main-residence/main-living-02.jpg",
    "assets/main-residence/main-living-03.jpg",
    "assets/main-residence/main-music-room.jpg",
    "assets/main-residence/main-porch-01.jpg",
    "assets/main-residence/main-porch-02.jpg",
    "assets/main-residence/main-porch-03.jpg",
    "assets/main-residence/main-primary-bathroom-02.jpg",
    "assets/main-residence/main-primary-bathroom-vanity.jpg",
    "assets/main-residence/main-primary-bedroom-02.jpg",
    "assets/main-residence/main-primary-bedroom-03.jpg",
    "assets/main-residence/main-shower-detail.jpg",
    "assets/main-residence/main-upstairs-landing-01.jpg",
    "assets/main-residence/main-upstairs-landing-02.jpg",
    "assets/main-residence/main-upstairs-landing-wide.jpg",
    "assets/main-residence/main-upstairs-library.jpg"
  ],
  "attached-residence": [
    "assets/attached-residence/attached-kitchen-hero.jpg",
    "assets/attached-residence/attached-living-hero.jpg",
    "assets/attached-residence/attached-bedroom-hero.jpg",
    "assets/attached-residence/attached-kitchen-wide.jpg",
    "assets/attached-residence/attached-bathroom-02.jpg",
    "assets/attached-residence/attached-bathroom-shower.jpg",
    "assets/attached-residence/attached-bathroom-vanity.jpg",
    "assets/attached-residence/attached-bedroom-02.jpg",
    "assets/attached-residence/attached-kitchen-dining.jpg",
    "assets/attached-residence/attached-kitchen-sink.jpg",
    "assets/attached-residence/attached-laundry.jpg",
    "assets/attached-residence/attached-living-01.jpg",
    "assets/attached-residence/attached-living-02.jpg",
    "assets/attached-residence/attached-living-03.jpg",
    "assets/attached-residence/attached-office.jpg",
    "assets/attached-residence/attached-porch-01.jpg",
    "assets/attached-residence/attached-porch-02.jpg",
    "assets/attached-residence/attached-porch-03.jpg",
    "assets/attached-residence/attached-utility.jpg"
  ],
  "guest-house": [
    "assets/guest-house/guest-exterior-front-hero.jpg",
    "assets/guest-house/guest-kitchen-hero.jpg",
    "assets/guest-house/guest-living-hero.jpg",
    "assets/guest-house/guest-bedroom-01-hero.jpg",
    "assets/guest-house/guest-bathroom-hero.jpg",
    "assets/guest-house/guest-backyard-01.jpg",
    "assets/guest-house/guest-backyard-02.jpg",
    "assets/guest-house/guest-bathroom-01.jpg",
    "assets/guest-house/guest-bathroom-02.jpg",
    "assets/guest-house/guest-bedroom-01-02.jpg",
    "assets/guest-house/guest-bedroom-02.jpg",
    "assets/guest-house/guest-chicken-coop.jpg",
    "assets/guest-house/guest-exterior-front-02.jpg",
    "assets/guest-house/guest-exterior-rear.jpg",
    "assets/guest-house/guest-kitchen-02.jpg",
    "assets/guest-house/guest-kitchen-03.jpg",
    "assets/guest-house/guest-living-01.jpg",
    "assets/guest-house/guest-living-02.jpg",
    "assets/guest-house/guest-living-03.jpg"
  ],
  "workshop": [
    "assets/workshop/workshop-interior-hero.jpg",
    "assets/workshop/workshop-exterior-open.jpg",
    "assets/workshop/workshop-exterior-closed.jpg",
    "assets/workshop/workshop-interior-02.jpg",
    "assets/workshop/workshop-interior-03.jpg",
    "assets/workshop/workshop-rear-side.jpg"
  ],
  "land-gardens": [
    "assets/land-gardens/garden-hero.jpg",
    "assets/land-gardens/raised-gardens.jpg",
    "assets/land-gardens/side-garden.jpg",
    "assets/land-gardens/play-area.jpg",
  ],
  "property-features": [
    "assets/property-features/rainwater-system.jpg",
    "assets/aerial/aerial-main-pool-angle.jpg",
    "assets/aerial/aerial-main-pool-topdown.jpg",
    "assets/workshop/workshop-rear-side.jpg"
  ],
  "pool-outdoor": [
    "assets/pool-outdoor/pool-hero.jpg",
    "assets/pool-outdoor/pool-wide.jpg",
    "assets/pool-outdoor/firepit.jpg"
  ],
  "aerial": [
    "assets/aerial/aerial-hero.jpg",
    "assets/aerial/aerial-featured.jpg",
    "assets/aerial/aerial-gallery-hero.jpg",
    "assets/aerial/aerial-compound-close.jpg",
    "assets/aerial/aerial-main-pool-angle.jpg",
    "assets/aerial/aerial-property-lines-close.jpg",
    "assets/aerial/aerial-finder-background.jpg",
    "assets/aerial/aerial-compound-topdown.jpg",
    "assets/aerial/aerial-context-01.jpg",
    "assets/aerial/aerial-context-02.jpg",
    "assets/aerial/aerial-context-03.jpg",
    "assets/aerial/aerial-context-04.jpg",
    "assets/aerial/aerial-context-05.jpg",
    "assets/aerial/aerial-main-pool-topdown.jpg",
    "assets/aerial/aerial-property-lines-01.jpg",
    "assets/aerial/aerial-property-lines-02.jpg",
    "assets/aerial/aerial-property-lines-03.jpg"
  ]
};
const CATEGORY_LABELS = {
  "main-residence": "Main Residence",
  "attached-residence": "Attached Residence",
  "guest-house": "Guest House",
  "workshop": "Workshop",
  "land-gardens": "Land + Gardens",
  "pool-outdoor": "Pool + Outdoor",
  "property-features": "Property Features",
  "aerial": "Aerial"
};
